export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      site_settings: {
        Row: {
          id: number;
          site_title_vi: string | null;
          site_title_en: string | null;
          site_description_vi: string | null;
          site_description_en: string | null;
          seo_keywords_vi: string[] | null;
          seo_keywords_en: string[] | null;
          og_image_url: string | null;
          twitter_handle: string | null;
          github_url: string | null;
          linkedin_url: string | null;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          site_title_vi?: string | null;
          site_title_en?: string | null;
          site_description_vi?: string | null;
          site_description_en?: string | null;
          seo_keywords_vi?: string[] | null;
          seo_keywords_en?: string[] | null;
          og_image_url?: string | null;
          twitter_handle?: string | null;
          github_url?: string | null;
          linkedin_url?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          site_title_vi?: string | null;
          site_title_en?: string | null;
          site_description_vi?: string | null;
          site_description_en?: string | null;
          seo_keywords_vi?: string[] | null;
          seo_keywords_en?: string[] | null;
          og_image_url?: string | null;
          twitter_handle?: string | null;
          github_url?: string | null;
          linkedin_url?: string | null;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      hero_section: {
        Row: {
          id: number;
          greeting_vi: string | null;
          greeting_en: string | null;
          name: string | null;
          headline_vi: string | null;
          headline_en: string | null;
          subheadline_vi: string | null;
          subheadline_en: string | null;
          roles_vi: string[] | null;
          roles_en: string[] | null;
          avatar_url: string | null;
          cta_primary_label_vi: string | null;
          cta_primary_label_en: string | null;
          cta_primary_href: string | null;
          cta_secondary_label_vi: string | null;
          cta_secondary_label_en: string | null;
          cta_secondary_href: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          greeting_vi?: string | null;
          greeting_en?: string | null;
          name?: string | null;
          headline_vi?: string | null;
          headline_en?: string | null;
          subheadline_vi?: string | null;
          subheadline_en?: string | null;
          roles_vi?: string[] | null;
          roles_en?: string[] | null;
          avatar_url?: string | null;
          cta_primary_label_vi?: string | null;
          cta_primary_label_en?: string | null;
          cta_primary_href?: string | null;
          cta_secondary_label_vi?: string | null;
          cta_secondary_label_en?: string | null;
          cta_secondary_href?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          greeting_vi?: string | null;
          greeting_en?: string | null;
          name?: string | null;
          headline_vi?: string | null;
          headline_en?: string | null;
          subheadline_vi?: string | null;
          subheadline_en?: string | null;
          roles_vi?: string[] | null;
          roles_en?: string[] | null;
          avatar_url?: string | null;
          cta_primary_label_vi?: string | null;
          cta_primary_label_en?: string | null;
          cta_primary_href?: string | null;
          cta_secondary_label_vi?: string | null;
          cta_secondary_label_en?: string | null;
          cta_secondary_href?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stats: {
        Row: {
          id: number;
          label_vi: string;
          label_en: string | null;
          value: number;
          suffix_vi: string | null;
          suffix_en: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          label_vi: string;
          label_en?: string | null;
          value: number;
          suffix_vi?: string | null;
          suffix_en?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          label_vi?: string;
          label_en?: string | null;
          value?: number;
          suffix_vi?: string | null;
          suffix_en?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      skills: {
        Row: {
          id: number;
          name_vi: string;
          name_en: string | null;
          category_vi: string | null;
          category_en: string | null;
          level_vi: string | null;
          level_en: string | null;
          icon_url: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          name_vi: string;
          name_en?: string | null;
          category_vi?: string | null;
          category_en?: string | null;
          level_vi?: string | null;
          level_en?: string | null;
          icon_url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          name_vi?: string;
          name_en?: string | null;
          category_vi?: string | null;
          category_en?: string | null;
          level_vi?: string | null;
          level_en?: string | null;
          icon_url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      approaches: {
        Row: {
          id: number;
          title_vi: string;
          title_en: string | null;
          subtitle_vi: string | null;
          subtitle_en: string | null;
          description_vi: string | null;
          description_en: string | null;
          icon: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          title_vi: string;
          title_en?: string | null;
          subtitle_vi?: string | null;
          subtitle_en?: string | null;
          description_vi?: string | null;
          description_en?: string | null;
          icon?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          title_vi?: string;
          title_en?: string | null;
          subtitle_vi?: string | null;
          subtitle_en?: string | null;
          description_vi?: string | null;
          description_en?: string | null;
          icon?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      experiences: {
        Row: {
          id: number;
          company: string;
          role_vi: string;
          role_en: string | null;
          location_vi: string | null;
          location_en: string | null;
          start_date: string;
          end_date: string | null;
          is_current: boolean;
          description_vi: string | null;
          description_en: string | null;
          highlights_vi: string[] | null;
          highlights_en: string[] | null;
          technologies: string[] | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          company: string;
          role_vi: string;
          role_en?: string | null;
          location_vi?: string | null;
          location_en?: string | null;
          start_date: string;
          end_date?: string | null;
          is_current?: boolean;
          description_vi?: string | null;
          description_en?: string | null;
          highlights_vi?: string[] | null;
          highlights_en?: string[] | null;
          technologies?: string[] | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          company?: string;
          role_vi?: string;
          role_en?: string | null;
          location_vi?: string | null;
          location_en?: string | null;
          start_date?: string;
          end_date?: string | null;
          is_current?: boolean;
          description_vi?: string | null;
          description_en?: string | null;
          highlights_vi?: string[] | null;
          highlights_en?: string[] | null;
          technologies?: string[] | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: number;
          slug: string;
          title_vi: string;
          title_en: string | null;
          short_description_vi: string | null;
          short_description_en: string | null;
          description_vi: string | null;
          description_en: string | null;
          thumbnail_url: string | null;
          repo_url: string | null;
          live_url: string | null;
          tags: string[] | null;
          featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          slug: string;
          title_vi: string;
          title_en?: string | null;
          short_description_vi?: string | null;
          short_description_en?: string | null;
          description_vi?: string | null;
          description_en?: string | null;
          thumbnail_url?: string | null;
          repo_url?: string | null;
          live_url?: string | null;
          tags?: string[] | null;
          featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          slug?: string;
          title_vi?: string;
          title_en?: string | null;
          short_description_vi?: string | null;
          short_description_en?: string | null;
          description_vi?: string | null;
          description_en?: string | null;
          thumbnail_url?: string | null;
          repo_url?: string | null;
          live_url?: string | null;
          tags?: string[] | null;
          featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
